// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvRxk6hMREuMJaajaNcNT-Sh6qjt_nHso',
    appId: '1:828165643684:web:94b16667ed0a72f2acb531',
    messagingSenderId: '828165643684',
    projectId: 'mannapin-48b47',
    authDomain: 'mannapin-48b47.firebaseapp.com',
    storageBucket: 'mannapin-48b47.firebasestorage.app',
    measurementId: 'G-10KEKD5ZT1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSq-nV_ION-RTBH9Auf8zJXYu7RvhbnqE',
    appId: '1:828165643684:android:037bbf5572d36c65acb531',
    messagingSenderId: '828165643684',
    projectId: 'mannapin-48b47',
    storageBucket: 'mannapin-48b47.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoUvfR6IAXsC-_JnoMKxFmpsGlOrDGeUE',
    appId: '1:828165643684:ios:f4a0a62a74778cc4acb531',
    messagingSenderId: '828165643684',
    projectId: 'mannapin-48b47',
    storageBucket: 'mannapin-48b47.firebasestorage.app',
    iosBundleId: 'com.example.temp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoUvfR6IAXsC-_JnoMKxFmpsGlOrDGeUE',
    appId: '1:828165643684:ios:f4a0a62a74778cc4acb531',
    messagingSenderId: '828165643684',
    projectId: 'mannapin-48b47',
    storageBucket: 'mannapin-48b47.firebasestorage.app',
    iosBundleId: 'com.example.temp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvRxk6hMREuMJaajaNcNT-Sh6qjt_nHso',
    appId: '1:828165643684:web:f0715e6593a305beacb531',
    messagingSenderId: '828165643684',
    projectId: 'mannapin-48b47',
    authDomain: 'mannapin-48b47.firebaseapp.com',
    storageBucket: 'mannapin-48b47.firebasestorage.app',
    measurementId: 'G-JGCXTTWG1D',
  );
}
